# Generated by Django 3.0.6 on 2020-05-14 01:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lodgment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lodges',
            new_name='Lodge',
        ),
    ]
